Importação de biblioteca

In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Algoritmos de classificação
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

# Acurácia
from sklearn.metrics import accuracy_score

Criação do dataframe

In [18]:
df = pd.read_csv('diamonds.csv')
# Pandas Series ------> unidimensional
# Pandas DataFrame

Análise exploratória

In [19]:
# Visualizar os primeiros registros
# Registros => Linhas
# Atributos => Colunas

df.head(10)

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0           1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1           2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2           3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3           4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4           5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
5           6   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94   
6           7   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95   
7           8   0.26  Very Good     H     SI1   61.9   55.0    337  4.07   
8           9   0.22       Fair     E     VS2   65.1   61.0    337  3.87   
9          10   0.23  Very Good     H     VS1   59.4   61.0    338  4.00   

      y     z  
0  3.98  2.43  
1  3.84  2.31  
2  4.07  2.31  
3  4.23  2.63  
4  4.35  2.75  
5  3.96  2.48  
6  3.98  2.47  
7  4.11  2.53  
8  3.78  2.49  
9  4.05  2.39

In [20]:
# Dimensões do dataframe
df.shape

(53940, 11)

In [21]:
print(f'O dataframe possui {df.shape[0]} registros e {df.shape[1]} atributos.')

O dataframe possui 53940 registros e 11 atributos.


In [22]:
# Infomações do conjunto de dados
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  53940 non-null  int64  
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  str    
 3   color       53940 non-null  str    
 4   clarity     53940 non-null  str    
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64  
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(6), int64(2), str(3)
memory usage: 4.5 MB


In [23]:
# Estatísticas descritivas dos atributos numéricos
df.describe()

Unnamed: 0         carat         depth         table         price  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000   
mean   26970.500000      0.797940     61.749405     57.457184   3932.799722   
std    15571.281097      0.474011      1.432621      2.234491   3989.439738   
min        1.000000      0.200000     43.000000     43.000000    326.000000   
25%    13485.750000      0.400000     61.000000     56.000000    950.000000   
50%    26970.500000      0.700000     61.800000     57.000000   2401.000000   
75%    40455.250000      1.040000     62.500000     59.000000   5324.250000   
max    53940.000000      5.010000     79.000000     95.000000  18823.000000   

                  x             y             z  
count  53940.000000  53940.000000  53940.000000  
mean       5.731157      5.734526      3.538734  
std        1.121761      1.142135      0.705699  
min        0.000000      0.000000      0.000000  
25%        4.710000      4.720000      2.910000  
50%        5.700000      5.710000      3.530000  
75%        6.540000      6.540000      4.040000  
max       10.740000     58.900000     31.800000

In [24]:
df['cut'].value_counts()

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [25]:
# preco = df[['price']] # Dataframe
preco = df['price'] # Serie
preco

0         326
1         326
2         327
3         334
4         335
         ... 
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64

In [26]:
type(preco)

pandas.Series

In [27]:
# Média aritmética da coluna de preço
media = preco.mean()
media

np.float64(3932.799721913237)

In [28]:
# Mediana aritmética da coluna de preço
mediana = preco.median()
mediana

np.float64(2401.0)

In [29]:
# Desvio Padrão da coluna de preço
desvio_padrao = preco.std()
desvio_padrao

np.float64(3989.439738146379)

In [30]:
print(f'A média aritmética da coluna de preços é U${media:.2f}.')
print(f'A mediana aritmética da coluna de preços é U${mediana:.2f}.')
print(f'O desvio padrão da coluna de preços é U${desvio_padrao:.2f}.')

A média aritmética da coluna de preços é U$3932.80.
A mediana aritmética da coluna de preços é U$2401.00.
O desvio padrão da coluna de preços é U$3989.44.


# **Dados da população**

A média aritmética da coluna de preços é U$3932.80.

A mediana aritmética da coluna de preços é U$2401.00.

O desvio padrão da coluna de preços é U$3989.44.

# **Geração de amostras**

In [31]:
# Regra --> 5% dos dados (2.700 registros)
# Primeira amostra --> valores iniciais (0 a 2.700)
# Segunda amostra --> valores intermediários (25.650 a 28.350)
# Terceira amostra --> valores finais (51.239 a 53.939)
# Quarta amostra --> valores aleatórios

In [32]:
# Amostra 1
a1 = df['price'].iloc[0:2700]
media_a1 = a1.mean()
desvio_padrao_a1 = a1.std()
mediana_a1 = a1.median()

print(f'A média aritmética da coluna de preços é U${media_a1:.2f}.')
print(f'A mediana aritmética da coluna de preços é U${mediana_a1:.2f}.')
print(f'O desvio padrão da coluna de preços é U${desvio_padrao_a1:.2f}.')

A média aritmética da coluna de preços é U$2709.73.
A mediana aritmética da coluna de preços é U$2940.00.
O desvio padrão da coluna de preços é U$785.84.


In [33]:
# Amostra 2
a2 = df['price'].iloc[25650:28350]
media_a2 = a2.mean()
desvio_padrao_a2 = a2.std()
mediana_a2 = a2.median()

print(f'A média aritmética da coluna de preços é U${media_a2:.2f}.')
print(f'A mediana aritmética da coluna de preços é U${mediana_a2:.2f}.')
print(f'O desvio padrão da coluna de preços é U${desvio_padrao_a2:.2f}.')

A média aritmética da coluna de preços é U$11601.85.
A mediana aritmética da coluna de preços é U$15618.00.
O desvio padrão da coluna de preços é U$7449.37.


In [34]:
# Amostra 3
a3 = df['price'].iloc[51239:53939]
media_a3 = a3.mean()
desvio_padrao_a3 = a3.std()
mediana_a3 = a3.median()

print(f'A média aritmética da coluna de preços é U${media_a3:.2f}.')
print(f'A mediana aritmética da coluna de preços é U${mediana_a3:.2f}.')
print(f'O desvio padrão da coluna de preços é U${desvio_padrao_a3:.2f}.')

A média aritmética da coluna de preços é U$2365.68.
A mediana aritmética da coluna de preços é U$2517.00.
O desvio padrão da coluna de preços é U$578.95.


In [35]:
# Amostra 4
a4 = df['price'].sample(frac=0.05, random_state=10) # SEED ("semente")
media_a4 = a4.mean()
desvio_padrao_a4 = a4.std()
mediana_a4 = a4.median()

print(f'A média aritmética da coluna de preços é U${media_a4:.2f}.')
print(f'A mediana aritmética da coluna de preços é U${mediana_a4:.2f}.')
print(f'O desvio padrão da coluna de preços é U${desvio_padrao_a4:.2f}.')

A média aritmética da coluna de preços é U$3834.44.
A mediana aritmética da coluna de preços é U$2401.00.
O desvio padrão da coluna de preços é U$3855.03.


# **Desafio**
Implementar um modelo preditivo de classificação para prever a classe do corte do diamante ("cut") com base nas características dimensionais "x", "y" e "z".

- Target --> cut
- features --> x, y e z

In [36]:
# Separação das features (X)
# Variáveis independentes
X = df[['x', 'y', 'z']]
X

x     y     z
0      3.95  3.98  2.43
1      3.89  3.84  2.31
2      4.05  4.07  2.31
3      4.20  4.23  2.63
4      4.34  4.35  2.75
...     ...   ...   ...
53935  5.75  5.76  3.50
53936  5.69  5.75  3.61
53937  5.66  5.68  3.56
53938  6.15  6.12  3.74
53939  5.83  5.87  3.64

[53940 rows x 3 columns]

In [37]:
# Separação do target (Y)
y = df['cut']
y

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...    
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: cut, Length: 53940, dtype: str

In [38]:
# Separação de dados de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [39]:
X_train.shape

(43152, 3)

In [40]:
y_train.shape

(43152,)

In [41]:
# Modelo com algoritmo KNN
modKNN = KNeighborsClassifier()

In [42]:
# Treinamento do modelo - KNN
modKNN.fit(X_train, y_train)

KNeighborsClassifier()

In [43]:
# Gerando previsões - KNN
y_predict = modKNN.predict(X_test)
y_predict

array(['Very Good', 'Premium', 'Ideal', ..., 'Very Good', 'Ideal',
       'Very Good'], shape=(10788,), dtype=object)

In [44]:
# Métrica --> Acurácia
acuracia = accuracy_score(y_test, y_predict)
print (f'A Acurácia modelo KNN é:{(100 * acuracia) : .2f}%')

A Acurácia modelo KNN é: 60.72%


In [45]:
# Modelo - Regressão Logística
modLog = LogisticRegression()

In [46]:
# Treinamento do modelo
modLog.fit(X_train, y_train)

c:\Users\Kaua\Downloads\repos\iot-fiap\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [47]:
# Gerando previsões
y_predict = modKNN.predict(X_test)
y_predict

array(['Very Good', 'Premium', 'Ideal', ..., 'Very Good', 'Ideal',
       'Very Good'], shape=(10788,), dtype=object)

In [48]:
# Métrica --> Acurácia
acuracia = accuracy_score(y_test, y_predict)
print (f'A Acurácia modelo usando Regressão Logística é:{(100 * acuracia) : .2f}%')

A Acurácia modelo usando Regressão Logística é: 60.72%


In [49]:
# Modelo - Árvore de descisão
modTree = DecisionTreeClassifier()

In [50]:
# Treinamento do modelo
modTree.fit(X_train, y_train)

DecisionTreeClassifier()

In [51]:
# Gerando previsões
y_predict = modTree.predict(X_test)
y_predict

array(['Ideal', 'Good', 'Ideal', ..., 'Very Good', 'Ideal', 'Good'],
      shape=(10788,), dtype=object)

In [52]:
# Métrica --> Acurácia
acuracia = accuracy_score(y_test, y_predict)
print (f'A Acurácia modelo usando Árvore de descisão é:{(100 * acuracia) : .2f}%')

A Acurácia modelo usando Árvore de descisão é: 56.59%
